apiVersion: v1
kind: Pod
metadata:
  name: podmysql
  labels:
    app: mysql-app
spec:
  containers:
    - name: mysql-container
      image: 329673269900.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
